### ISSUE TITLE
UI - issue

### ISSUE THREAD

**Issue by babsjohnson** [FEC-House-Stark/rfc2209-front-end-capstone-HouseStark#62]
There is not much differentiation between answers in the answers list; consider adding more padding or a border to increase legibility 

It would be a good idea to handle broken images and make it not possible to click a broken image into a modal [OPTIONAL] [NIGHTMARE MODE]

**Comment by xialin0702** [comment]
Lol, looks like the button title tricked us, in the detail it says 'The list will by default only display up to 2 questions asked. If there are more than 2 questions that have been asked for the given product, a button for “More Answered Questions” will appear below the list. '

**Comment by xialin0702** [comment]
added 10px to padding-bottom to each answer container. fixed
