### ISSUE TITLE
QA - Filter Question list

### ISSUE THREAD

**Issue by babsjohnson** [FEC-House-Stark/rfc2209-front-end-capstone-HouseStark#64]
filter questions list only to include questions that have an answer on rendering more, while still allowing the search to filter all questions

https://github.com/FEC-House-Stark/rfc2209-front-end-capstone-HouseStark/blob/ada66600e6767534556b1faab7204af1b5440f05/client/src/components/QandA/components/Question_View.jsx#L48

**Comment by babsjohnson** [comment]
@xialin0702

**Comment by xialin0702** [comment]
Lol, looks like the button title tricked us, in the detail it says 'The list will by default only display up to 2 questions asked. If there are more than 2 questions that have been asked for the given product, a button for “More Answered Questions” will appear below the list. '
@babsjohnson
